image: node:14.2.0

cache: &global_cache
  key: "${CI_COMMIT_REF_SLUG}"
  paths:
    - .npm/

# install npm packages before all stages, using cache as source
before_script:
  - npm install --cache .npm --prefer-offline --no-audit
  # check if ng client is already installed and create a symlink if needed
  - test -e /usr/local/bin/ng || ln -s $PWD/node_modules/.bin/ng /usr/local/bin/ng
  # check if webdriver-manager is already installed and create a symlink if needed
  - test -e /usr/local/bin/webdriver-manager || ln -s $PWD/node_modules/.bin/webdriver-manager /usr/local/bin/webdriver-manager

stages:
  - static_analysis
  - test

static_analysis:
  stage: static_analysis
  script:
    - ng lint
    - npm audit --audit-level=moderate
    - node_modules/.bin/linthtml .

ng-test:
  image: trion/ng-cli-karma:9.1.5
  stage: test
  cache:
    # inherit all global cache settings
    <<: *global_cache
    # override the policy to only pull
    policy: pull
  script:
    # run Karma/Jasmine unit tests
    - ng test --no-watch --no-progress --browsers=ChromeHeadlessCI
    # run Protractor end-to-end tests. Chrome and ChromeDriver need to be in sync
    # in ng-cli-karma image, protractor.conf.ci.js and here
    - webdriver-manager update --versions.chrome=81.0.4044.138
    - ng e2e --protractor-config e2e/protractor.conf.ci.js
